#include <inttypes.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#define BLOCK_SIZE 32
#define WORD_SIZE 16
#define WORD_TYPE uint16_t
#define WORD_IN_TYPE SCNx16
#define WORD_OUT_TYPE PRIx16
#define WORD_CONSTANT_TYPE UINT16_C
#define WORD_PARITY_FUNCTION __builtin_parity
#define WORD_MASK 0xffff
#define ROUNDS 2

WORD_TYPE MATRICES[ROUNDS + 1][BLOCK_SIZE][2] = {
    {{WORD_CONSTANT_TYPE(128), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(256), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(512), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(1024), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(2048), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(4096), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(8192), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(16384), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(32768), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(1), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(2), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(4), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(8), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(16), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(32), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(64), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(1)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(2)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(4)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(8)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(16)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(32)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(64)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(128)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(256)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(512)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(1024)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(2048)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(4096)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(8192)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(16384)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(32768)}},
    {{WORD_CONSTANT_TYPE(29097), WORD_CONSTANT_TYPE(1181)}, {WORD_CONSTANT_TYPE(6592), WORD_CONSTANT_TYPE(32553)}, {WORD_CONSTANT_TYPE(47281), WORD_CONSTANT_TYPE(13365)}, {WORD_CONSTANT_TYPE(10925), WORD_CONSTANT_TYPE(11170)}, {WORD_CONSTANT_TYPE(14537), WORD_CONSTANT_TYPE(26383)}, {WORD_CONSTANT_TYPE(4195), WORD_CONSTANT_TYPE(40010)}, {WORD_CONSTANT_TYPE(24073), WORD_CONSTANT_TYPE(33034)}, {WORD_CONSTANT_TYPE(5251), WORD_CONSTANT_TYPE(24611)}, {WORD_CONSTANT_TYPE(30221), WORD_CONSTANT_TYPE(36592)}, {WORD_CONSTANT_TYPE(2050), WORD_CONSTANT_TYPE(15278)}, {WORD_CONSTANT_TYPE(61718), WORD_CONSTANT_TYPE(44882)}, {WORD_CONSTANT_TYPE(41931), WORD_CONSTANT_TYPE(1742)}, {WORD_CONSTANT_TYPE(63161), WORD_CONSTANT_TYPE(19761)}, {WORD_CONSTANT_TYPE(25275), WORD_CONSTANT_TYPE(6419)}, {WORD_CONSTANT_TYPE(18077), WORD_CONSTANT_TYPE(56863)}, {WORD_CONSTANT_TYPE(65320), WORD_CONSTANT_TYPE(17699)}, {WORD_CONSTANT_TYPE(40345), WORD_CONSTANT_TYPE(12641)}, {WORD_CONSTANT_TYPE(17850), WORD_CONSTANT_TYPE(41943)}, {WORD_CONSTANT_TYPE(22859), WORD_CONSTANT_TYPE(5224)}, {WORD_CONSTANT_TYPE(9914), WORD_CONSTANT_TYPE(35334)}, {WORD_CONSTANT_TYPE(33516), WORD_CONSTANT_TYPE(53865)}, {WORD_CONSTANT_TYPE(21937), WORD_CONSTANT_TYPE(36948)}, {WORD_CONSTANT_TYPE(7698), WORD_CONSTANT_TYPE(64163)}, {WORD_CONSTANT_TYPE(26012), WORD_CONSTANT_TYPE(23077)}, {WORD_CONSTANT_TYPE(403), WORD_CONSTANT_TYPE(45840)}, {WORD_CONSTANT_TYPE(56955), WORD_CONSTANT_TYPE(36457)}, {WORD_CONSTANT_TYPE(19504), WORD_CONSTANT_TYPE(51459)}, {WORD_CONSTANT_TYPE(50976), WORD_CONSTANT_TYPE(3571)}, {WORD_CONSTANT_TYPE(36237), WORD_CONSTANT_TYPE(39954)}, {WORD_CONSTANT_TYPE(21368), WORD_CONSTANT_TYPE(18849)}, {WORD_CONSTANT_TYPE(41510), WORD_CONSTANT_TYPE(21640)}, {WORD_CONSTANT_TYPE(52070), WORD_CONSTANT_TYPE(65287)}},
    {{WORD_CONSTANT_TYPE(512), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(1024), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(2048), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(4096), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(8192), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(16384), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(32768), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(1), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(2), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(4), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(8), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(16), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(32), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(64), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(128), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(256), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(1)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(2)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(4)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(8)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(16)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(32)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(64)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(128)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(256)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(512)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(1024)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(2048)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(4096)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(8192)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(16384)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(32768)}}
};

WORD_TYPE VECTORS[ROUNDS + 1][2] = {{WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(0)}, {WORD_CONSTANT_TYPE(19091), WORD_CONSTANT_TYPE(35970)}, {WORD_CONSTANT_TYPE(0), WORD_CONSTANT_TYPE(0)}};

void matrix_vector_product(WORD_TYPE matrix[BLOCK_SIZE][2], WORD_TYPE xy[2], WORD_TYPE res[2]) {
    for (size_t i = WORD_SIZE; i-- > 0;) {
        res[0] = (res[0] << 1) | ((WORD_TYPE) WORD_PARITY_FUNCTION((matrix[i][0] & xy[0]) ^ (matrix[i][1] & xy[1])));
        res[1] = (res[1] << 1) | ((WORD_TYPE) WORD_PARITY_FUNCTION((matrix[WORD_SIZE + i][0] & xy[0]) ^ (matrix[WORD_SIZE + i][1] & xy[1])));
    }
}

void vector_addition(WORD_TYPE vector[2], WORD_TYPE xy[2]) {
    xy[0] ^= vector[0];
    xy[1] ^= vector[1];
}

void modular_addition(WORD_TYPE xy[2]) {
    xy[0] = (xy[0] + xy[1]) & WORD_MASK;
}

void modular_subtraction(WORD_TYPE xy[2]) {
    xy[0] -= xy[1];
}

int main(int argc, char *argv[]) {
    WORD_TYPE xy[2];
    WORD_TYPE res[2];
    if (argc < 3) {
        return -1;
    } else {
        sscanf(argv[1], "%" WORD_IN_TYPE, &xy[0]);
        sscanf(argv[2], "%" WORD_IN_TYPE, &xy[1]);
        res[0] = 0;
        res[1] = 0;
        matrix_vector_product(MATRICES[0], xy, res);
        vector_addition(VECTORS[0], res);
        modular_addition(res);
        vector_addition(VECTORS[1], res);
        xy[0] = 0;
        xy[1] = 0;
        matrix_vector_product(MATRICES[1], res, xy);
        modular_subtraction(xy);
        vector_addition(VECTORS[2], xy);
        res[0] = 0;
        res[1] = 0;
        matrix_vector_product(MATRICES[2], xy, res);
        printf("%" WORD_OUT_TYPE " %" WORD_OUT_TYPE "\n", res[0], res[1]);
    }
}
